# Usa a imagem debian-slim, que é um bom equilíbrio entre tamanho e compatibilidade
FROM node:22-slim

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos de dependência primeiro para aproveitar o cache do Docker
# Copiando o yarn.lock para garantir uma instalação consistente com o yarn
COPY package.json ./
COPY yarn.lock ./

# AQUI ESTA A CORREÇÃO FINAL:
# Usando o nome do pacote correto 'netcat-openbsd' para Debian.
RUN apt-get update && apt-get install -y git netcat-openbsd

# Instala as dependências do projeto USANDO YARN para consistência
RUN yarn install --frozen-lockfile --ignore-scripts --network-timeout-100000

# Copia o restante do código da sua aplicação
COPY . .

# Define a variável de ambiente para desenvolvimento
ENV NODE_ENV=development

# Expõe a porta que a sua API vai escutar
EXPOSE 21165

# NOVO COMANDO DE INICIALIZAÇÃO:
# Este comando usa um loop para testar a conexão com o banco de dados
# na porta 27017. Ele só executa "yarn start" DEPOIS que a conexão for bem-sucedida.
CMD ["/bin/sh", "-c", "while ! nc -z mongo 27017; do sleep 1; done; yarn start"]
